### PR TITLE
Paint substep walk

### PR DESCRIPTION
**Pull request by theis999**
#165  Paint steps in steplist when extra substep walks are added.

It is perhaps not the pretties:
image

Also added a translation map to technologies.

### CODE REVIEW

**Comment by MortenTobiasNielsen** [comment]
For some reason I haven't noticed this pull request - sorry. I think it would be nice if it was painted red and a comment like "Walk step added" was there - which should be "caught" in lua, so it isn't printed out.

**Comment by theis999** [comment]
I can paint it red, i don't know if agree that it should be Error color.
I can't add a comment, as that would either override a comment that is already there or adds a comment that shouldn't be there. Of course _i can_, i just don't think it is a good idea.

**Comment by MortenTobiasNielsen** [comment]
Agreed - wasn't the best ideas. :D

**Review by MortenTobiasNielsen — APPROVED** [review]
I am still a little worried that the user won't really know why the comment column is colored, but I on the other hand have no better alternative, so lets try it out. :)

Nice to get the tech into a translation table.

**Pull request merged**
