### PR TITLE
Fix put module

### PR DESCRIPTION
**Pull request by theis999**
Reversed the order, of insert and remove items to make sure we can add all of the items we want before removing them.

### CODE REVIEW

**Comment by MortenTobiasNielsen** [comment]
Seems like we need some extra safe guards:
image

It happened while putting (32 iron plates into an assembling machine). Not sure why the code change would cause a negative number.

**Comment by theis999** [comment]
I couldn't easily force the issue. My concern is at this:

image
If either removalable_items or insertable_items returns a negative value. Then math.min also returns a negative value.

**Comment by MortenTobiasNielsen** [comment]
Surely, but in what scenario would the character carry a negative amount or the buildings inserting into only be able to receive a negative amount?

**Comment by theis999** [comment]
I honestly don't see how any of the code could cause the crash you experienced. Unless it isn't a negativ value but just a zero?

**Comment by theis999** [comment]
image
Step 8 - crashes the game like you reported

**Review by MortenTobiasNielsen — APPROVED** [review]
Nice to get the warning, so it is clear that the step isn't configured correctly.

**Pull request merged**
